---

sudo: false

dist: trusty

language: php

before_install:
  - cp .auth.json ~/.composer/auth.json
  - composer self-update
  - composer global require drush/drush:@stable
  - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
  - cd ..
  - git clone --branch 8.0.x https://git.drupal.org/project/drupal.git
  - cd drupal
  - curl -sL https://www.drupal.org/files/issues/2664274-37.patch | patch -p1
  - drush --yes site-install testing --db-url=sqlite://sites/default/files/.ht.sqlite
  - drush dl composer_manager
  - drush --yes pm-enable composer_manager
  - php modules/composer_manager/scripts/init.php
  - composer drupal-update
  - mv ../oauth2-drupal-module modules/authbucket_oauth2
  - composer drupal-update
  - drush --yes pm-enable authbucket_oauth2
  - drush --yes pm-enable simpletest

script:
  - php core/scripts/run-tests.sh --php `which php` PHPUnit
