---

sudo: false

dist: trusty

language: php

before_install:
  - composer self-update
  - composer global require drush/drush:@stable
  - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
  - drush core-quick-drupal --yes --root=drupal --core=drupal-8.0.x --profile=testing --no-server --db-url=sqlite://sites/default/files/.ht.sqlite
  - cd drupal

script:
  - phpunit -c core/phpunit.xml.dist
