---

sudo: false

dist: trusty

language: php

before_install:
  - composer self-update
  - composer global require drush/drush:@stable
  - export PATH="$PATH:$HOME/.composer/vendor/bin"

install:
  - cd ..
  - git clone --branch 8.0.x https://git.drupal.org/project/drupal.git
  - cd drupal
  - composer update
  - drush site-install testing --yes --db-url=sqlite://sites/default/files/.ht.sqlite

script:
  - phpunit -c core/phpunit.xml.dist
